[Fri Apr 10 22:12:27 2015] [error] ERROR:ajax_flask.app:Exception on / [POST]
[Fri Apr 10 22:12:27 2015] [error] Traceback (most recent call last):
[Fri Apr 10 22:12:27 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
[Fri Apr 10 22:12:27 2015] [error]     response = self.full_dispatch_request()
[Fri Apr 10 22:12:27 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
[Fri Apr 10 22:12:27 2015] [error]     rv = self.handle_user_exception(e)
[Fri Apr 10 22:12:27 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
[Fri Apr 10 22:12:27 2015] [error]     reraise(exc_type, exc_value, tb)
[Fri Apr 10 22:12:27 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
[Fri Apr 10 22:12:27 2015] [error]     rv = self.dispatch_request()
[Fri Apr 10 22:12:27 2015] [error]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
[Fri Apr 10 22:12:27 2015] [error]     return self.view_functions[rule.endpoint](**req.view_args)
[Fri Apr 10 22:12:27 2015] [error]   File "/app/ajax_flask/app.py", line 43, in python_function
[Fri Apr 10 22:12:27 2015] [error]     network = make_enr_clust.main(inst_genes, num_terms, 'jaccard')
[Fri Apr 10 22:12:27 2015] [error]   File "/app/ajax_flask/make_enr_clust.py", line 7, in main
[Fri Apr 10 22:12:27 2015] [error]     d3_json = make_enrichment_clustergram(enr, num_terms, dist_type)
[Fri Apr 10 22:12:27 2015] [error]   File "/app/ajax_flask/make_enr_clust.py", line 51, in make_enrichment_clustergram
[Fri Apr 10 22:12:27 2015] [error]     clust_order = d3_clustergram.cluster_row_and_column( nodes, data_mat, dist_type, enr )
[Fri Apr 10 22:12:27 2015] [error]   File "/app/ajax_flask/d3_clustergram.py", line 105, in cluster_row_and_column
[Fri Apr 10 22:12:27 2015] [error]     Z = hier.dendrogram( Y )
[Fri Apr 10 22:12:27 2015] [error]   File "/usr/lib/python2.7/dist-packages/scipy/cluster/hierarchy.py", line 2177, in dendrogram
[Fri Apr 10 22:12:27 2015] [error]     contraction_marks=contraction_marks)
[Fri Apr 10 22:12:27 2015] [error]   File "/usr/lib/python2.7/dist-packages/scipy/cluster/hierarchy.py", line 1711, in _plot_dendrogram
[Fri Apr 10 22:12:27 2015] [error]     axis = matplotlib.pylab.gca()
[Fri Apr 10 22:12:27 2015] [error]   File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 701, in gca
[Fri Apr 10 22:12:27 2015] [error]     ax =  gcf().gca(**kwargs)
[Fri Apr 10 22:12:27 2015] [error]   File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 369, in gcf
[Fri Apr 10 22:12:27 2015] [error]     return figure()
[Fri Apr 10 22:12:27 2015] [error]   File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 343, in figure
[Fri Apr 10 22:12:27 2015] [error]     **kwargs)
[Fri Apr 10 22:12:27 2015] [error]   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 80, in new_figure_manager
[Fri Apr 10 22:12:27 2015] [error]     window = Tk.Tk()
[Fri Apr 10 22:12:27 2015] [error]   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1712, in __init__
[Fri Apr 10 22:12:27 2015] [error]     self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
[Fri Apr 10 22:12:27 2015] [error] TclError: no display name and no $DISPLAY environment variable
